# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DivBin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DivBin
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftVideoBackground'
  pod 'Clarifai'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'ImagePicker'
  pod 'Eureka'

end
